# https://hub.docker.com/_/python/
image: python:3.5

# stages are jobs
# jobs are independent
stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install nose
    - nosetests -x