# https://hub.docker.com/_/python/
image: python:3.5

# stages are jobs
# jobs are independent
stages:
  - test

test:
  stage: test
  script:
    - echo "deb http://archive.ubuntu.com/ubuntu precise main universe" >> /etc/apt/sources.list
    - apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 40976EAF437D05B5
    - apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
    - apt-get update
    - apt-get install -y freetds-dev
    - pip install -r requirements.txt
    - pip install --editable .
    - pip install nose
    - zephyr configure --first-run
    - nosetests -x
